### ISSUE TITLE
How to seek forward to the end of the outer block

### ISSUE THREAD

**Issue by devnut** [exponent-io/jsonpath#4]
In this example:

```
import "github.com/exponent-io/jsonpath"

var j = []byte(`[
  {"Space": "YCbCr", "Point": {"Y": 255, "Cb": 0, "Cr": -10}},
  {"Space": "RGB",   "Point": {"R": 98, "G": 218, "B": 255}}
]`)

w := json.NewDecoder(bytes.NewReader(j))
var v interface{}

w.SeekTo(1, "Point", "G")
w.Decode(&v) // v is 218

```

How would one SeekTo the closing "]" to ensure all the content was read?  Or is that not possible?

Note: in this case it isn't really feasible to look for an EOF.  The actual JSON payload looks more like this and the goal is to seek to the second array after processing the first one:

```
[
  {"Space": "YCbCr", "Point": {"Y": 255, "Cb": 0, "Cr": -10}},
  {"Space": "RGB",   "Point": {"R": 98, "G": 218, "B": 255}}
]
[
  {"Space": "YCbCr", "Point": {"Y": 255, "Cb": 0, "Cr": -10}},
  {"Space": "RGB",   "Point": {"R": 98, "G": 218, "B": 255}}
]

```
-- Greg

**Comment by peterwald** [comment]
We don't have a built-in API for this but you can easily accomplish the same thing by reading tokens until the `.Path()` is empty (or at whatever position you'd like).

```golang
var err error
for err == nil && len(w.Path()) > 0 {
    _, err = w.Token()
}
```

**Comment by peterwald** [comment]
After thinking about it a bit more, I think this was an oversight in the `SeekTo()` API. I've made a PR that will allow for the same effect by calling `w.SeekTo()` at the end. In this case, it seeks forward until the path is empty, which it would be at the end of the JSON object.

#5

**Comment by peterwald** [comment]
You can now use either the `Token` loop method above, or with the change I just merged you can call `SeekTo` with no arguments.
